### ISSUE TITLE
Feature Request: add an option to exempt certain commands

### ISSUE THREAD

**Issue by U5B** [Ran-helo/uwu#2]
A configuration option to uwuify only certain commands, if they are prefixed with a command used for chat.
For example: On Hypixel, the command prefix for allchat is `/ac`. This command would not be uwuified, but the message after would be.
The ability to add multiple exceptions or use regex to customize which part of the command to be uwuified would also be very useful.
For example: `/\/msg ([0-9a-zA-Z_]{1,16})/` would exclude the command `/msg playername`

**Comment by Ran-helo** [comment]
I think the current way to do this would be to uwuify the last matching regex
For example `/msg /([0-9a-zA-Z_]{1,256})/ /([0-9a-zA-Z_]{1,256})/` would be like `/msg <playerName> <uwuifiedMessage>`

I can't find a way to do it other than this _hopefully someone else could PR this and do it in a better way_

**Comment by Ran-helo** [comment]
Done!
