### ISSUE TITLE
f3 menu.

### ISSUE THREAD

**Issue by CodeF53** [Ran-helo/uwu#3]
When I downwoaded this mod I weawwy x3 hoped i-it w-wouwd dwamaticawwy impwuv the UwUabiwity of minyecwaft.

I-it wowks gweat in most wespects, but t-to my dismay, when I openyed x3 the F3 m-menyu, wiggwing in anticipation fow the beauty that w-wouwd be waid out befowe me, I was met with nyothing but disappointment. 
![image](https://user-images.githubusercontent.com/37855219/163524768-891d96bf-535e-4c50-be76-9f7d6fbcf012.png)
Wwought with dismay, I wubbed my eyes, I couwdn't b-bewieve my eyes, the F3 scween wemainyed untouched?!?1

Vawve, pwease fix

Oh my god I never want to type like this ever again

**Comment by Ran-helo** [comment]
i-i wuved the typing >~<
